spring.application.name=chatbot

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/chatbot_db
spring.datasource.username=root
spring.datasource.password=Root@123

# Gemini API
gemini.api.key=AQ.Ab8RN6Ltx4bG1sk_WJaylVZArCPQ6MqWp6fRUt1VQ7clFfN3ww
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
 #JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8081